---
- hosts: ec2-client
  tasks:
    - include_vars:
        file: ansible_variables.yml
        name: var

    - file:
        path: /home/{{ var.user_2 }}/all/wiki/code
        state: directory
        mode: "0755"

    - ansible.posix.synchronize:
        src: "{{ var.wiki_code_path_local }}/{{ item }}"
        dest: "{{ var.wiki_code_path_remote_2 }}"
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.terraform"
          - "--exclude=.terraform.lock.hcl"
      with_items:
        - cloud-aws
        - svc-iac
        - svc-web
        - svc-conn
        - svc-repo
        - lang-code

    - ansible.builtin.shell:
        cmd: echo "{{ var.wiki_code_path_remote_2 }}/{{ code }} {{ var.user_2 }} {{ var.dist_2 }} {{ var.domain_2 }}"
      register: command

    - ansible.builtin.debug:
        var: command.stdout

    - ansible.builtin.shell:
        cmd: sh {{ var.wiki_code_path_remote_2 }}/{{ code }} {{ var.user_2 }} {{ var.dist_2 }} {{ var.domain_2 }}
